// angular-app/src/app/Components/details-page/details-page.component.ts
import { Result } from './../../Models/ResultsData';
import { DataService } from './../../Services/data-service/data-service.service';
import {ParamMap, ActivatedRoute} from '@angular/router';
import { Component, OnInit } from '@angular/core';
import 'rxjs/add/operator/switchMap';
import { Location } from '@angular/common';

@Component({
  selector: 'app-details-page',
  templateUrl: './details-page.component.html',
  styleUrls: ['./details-page.component.css']
})
export class DetailsPageComponent implements OnInit {
  result: Result = null;
  selectedTab: number = 1;

  constructor(private _dataService: DataService,
    private _location: Location,
    private _route: ActivatedRoute) { }

  ngOnInit() {
    this._route.paramMap
    .switchMap((params: ParamMap) => this._dataService.GetResultsById(+params.get('id')))
    .subscribe(result => this.result = result);
  }

  changeTab(id: number){
    this.selectedTab = id;
  }

  goBack() {
    this._location.back();
  }
}

<div class="DetailsPage col-lg-12">
    <div class="DetailsPage-Card card">
        <div class="DetailsPage-Toolbar card-header">
            <div class="col-lg-8">
                <h1>{{result.full_name}}</h1>
            </div>
            <div class="DetailsPage-BackBtn col-lg-4">
                <input class="btn btn-default" type="button" value="Back" (click)="goBack()" />
            </div>
        </div>
        <div class="card-block">
          <div class="DetailsPage-Nav col-lg-3">
            <ul class="nav nav-pills nav-justified">
              <li class="nav-item">
                <a [ngClass]="{'nav-link': true, 'active': selectedTab === 1}" (click)="changeTab(1)" role="tab">Personal Information</a>
              </li>
              <li class="nav-item">
                <a [ngClass]="{'nav-link': true, 'active': selectedTab === 2}" (click)="changeTab(2)" role="tab">Location Information</a>
              </li>
            </ul>
          </div>
          <div class="tab-content col-lg-9">
            <div [ngClass]="{'tab-pane': true, 'active': selectedTab === 1}" id="details">
                <div className="col-lg-12">
                    <p>First Name: {{result.first_name}}</p>
                    <p>Last Name: {{result.last_name}}</p>
                    <p>Language: {{result.language}}</p>
                    <p>Email: {{result.email}}</p>
                    <p>Gender: {{result.gender}}</p>
                    <p>Eye Color: {{result.eye_color}}</p>
                </div>
            </div>
            <div [ngClass]="{'tab-pane': true, 'active': selectedTab === 2}" id="location">
                <div className="col-lg-12">
                    <p>City: {{result.city}}</p>
                    <p>State: {{result.state}}</p>
                </div>
            </div>
          </div>
        </div>
    </div>
</div>

// react-app/src/Components/DetailsPage/DetailsPage.js
import React, { Component } from 'react';
import { Button, Tab, Row, Col, Nav, NavItem } from 'react-bootstrap';
import { GetResultById } from '../../Service/DataService';

import './DetailsPage.css';

export default class DetailsPage extends Component {
    constructor(props){
        super(props);
        this.state = {
            selectedTab: 'details',
            result: null
        };
    }
    componentDidMount(){
        GetResultById(parseInt(this.props.match.params.id, 10)).then((data) => this.setState({result: data}));
        if(typeof(this.props.match.params.tab) !== 'undefined')
            this.setState({selectedTab : this.props.match.params.tab});
        console.log(this.props.match.params.id + ' ' + this.props.match.params.tab);
    }
    changeTab(id){
        this.setState({selectedTab: id});
    }
    render () {
        if(this.state.result === null) {
            return (
                <div>
                    <div className="DetailsPage col-lg-12">
                        <div className="panel panel-default">
                            <div className="DetailsPage-Toolbar col-lg-12 panel-heading">
                                Loading...
                            </div>
                            <div className="panel-body">
                                Loading...
                            </div>
                        </div>
                    </div>
                </div>
            );
        }
        return (
            <div className="DetailsPage col-lg-12">
                <div className="panel panel-default">
                    <div className="DetailsPage-Toolbar col-lg-12 panel-heading">
                        <div className="col-lg-8">
                            <h1>{this.state.result.full_name}</h1>
                        </div>
                        <div className="DetailsPage-BackBtn col-lg-4">
                            <Button onClick={this.props.history.goBack}>Back</Button>
                        </div>
                    </div>
                    <div className="panel-body">
                        <Tab.Container activeKey={this.state.selectedTab}>
                            <Row className="clearfix">
                                <Col sm={4}>
                                    <Nav bsStyle="pills" stacked>
                                        <NavItem eventKey="details" onClick={() => this.changeTab('details')}>
                                            Personal Information
                                        </NavItem>
                                        <NavItem eventKey="location" onClick={() => this.changeTab('location')}>
                                            Location Information
                                        </NavItem>
                                    </Nav>
                                </Col>
                                <Col sm={8}>
                                    <Tab.Content className="DetailsPage-TabContent" animation>
                                        <Tab.Pane eventKey="details">
                                            <div className="col-lg-12">
                                                <p>First Name: {this.state.result.first_name}</p>
                                                <p>Last Name: {this.state.result.last_name}</p>
                                                <p>Language: {this.state.result.language}</p>
                                                <p>Email: {this.state.result.email}</p>
                                                <p>Gender: {this.state.result.gender}</p>
                                                <p>Eye Color: {this.state.result.eye_color}</p>
                                            </div>
                                        </Tab.Pane>
                                        <Tab.Pane eventKey="location">
                                            <div className="col-lg-12">
                                                <p>City: {this.state.result.city}</p>
                                                <p>State: {this.state.result.state}</p>
                                            </div>
                                        </Tab.Pane>
                                    </Tab.Content>
                                </Col>
                            </Row>
                        </Tab.Container>
                    </div>
                </div>
            </div>
        );
    }
}
