// react-app/src/Components/ResultsPage/ResultsPage.js
import React, { Component } from 'react';
import { GetFilters } from '../../Service/ManageFilters';
import { GetResults } from '../../Service/DataService';
import { Button } from 'react-bootstrap';
import Autocomplete from '../Common/Autocomplete/Autocomplete';

import './ResultsPage.css';

export default class ResultsPage extends Component {
    constructor(props) {
        super(props);

        this.state = {
            filters: [],
            results: []
        }
    }
    componentDidMount(){
        this.updateResultsPage();
    }
    updateResultsPage() {
        GetResults().then((data) => {this.setState({results: data})});
        this.setState({filters: GetFilters()});
    }
    goToDetails(id){
        this.props.history.push(`/details/${id}`);
    }
    render () {
        return (
            <div className="ResultsPage container-fluid">
                <div className="ResultsPage-AutoCompleteDiv row">
                    <div className="col-lg-12">
                        <div className="col-lg-1"><h4>Search:</h4></div> 
                        <div className="col-lg-11"><Autocomplete /></div> 
                    </div>
                </div>
                <div className="ResultsPage-Toolbar row col-lg-12">
                    <Button onClick={this.props.history.goBack}>Back</Button>
                </div>
                <div className="ResultsPage-Header row col-lg-12">
                    <h1>Results: {this.state.results.length}</h1>
                </div>
                <div className="row">
                    <div className="col-lg-1">
                        <p>Filter:</p>
                    </div>
                    <div className="col-lg-11">
                        {this.state.filters.map((filter) => 
                            <div className="ResultsPage-Filters">
                                <span className="glyphicon glyphicon-ok" aria-hidden="true"></span>{' '+filter.value}
                            </div>
                        )}
                    </div>
                </div>
                <div className="ResultsPage-List row">
                    {this.state.results.map((listItem) =>
                        <div className="ResultsPage-ListItem col-lg-12">
                            <div className="panel panel-default">
                            <div className="panel-heading" onClick={() => this.goToDetails(listItem.id)}>{listItem.full_name}</div>
                                <div className="panel-body">
                                    <div className="col-lg-4">City: {listItem.city}</div>
                                    <div className="col-lg-4">State: {listItem.state}</div>
                                </div>
                            </div>
                        </div>
                    )}
                </div>
            </div>
        );
    }
}

// angular-app/src/app/Components/results-page/results-page.component.ts
import { Filter } from './../../Models/FiltersData';
import { Router } from '@angular/router';
import { Result } from './../../Models/ResultsData';
import { DataService } from './../../Services/data-service/data-service.service';
import {FiltersService} from '../../Services/filters-service/filters-service.service';
import { Component, OnInit } from '@angular/core';
import { Location } from '@angular/common';

@Component({
  selector: 'app-results-page',
  templateUrl: './results-page.component.html',
  styleUrls: ['./results-page.component.css']
})
export class ResultsPageComponent implements OnInit {
  results: Result[] = [];
  filters: Filter[] = [];

  constructor(private _dataService: DataService,
    private _filterService: FiltersService,
    private _location: Location,
    private _router: Router) { }

  ngOnInit() {
    this.updateResultsPage();
  }

  updateResultsPage() {
    this.filters = this._filterService.GetFilters();
    this._dataService.GetResults(this.filters)
      .then(results => this.results = results)
      .catch(this.handleError);
  }

  goToDetails(id) {
    this._router.navigate(['/details', id]);
  }

  goBack() {
    this._location.back();
  }

  /**
   * Handle errors from the requests
   */
  private handleError(error: any): Promise<any> {
    console.error('An error occurred', error);
    return Promise.reject(error.message || error);
  }
}

<div class="ResultsPage container-fluid">
    <div class="ResultsPage-AutoCompleteDiv row">
        <div class="container-fluid col-lg-12">
            <div class="row">
                <div class="col-lg-1"><h6>Search:</h6></div>
                <div class="col-lg-11"><app-autocomplete (onClick)="updateResultsPage()"></app-autocomplete></div>
            </div>
        </div>
    </div>
    <div class="ResultsPage-Toolbar row col-lg-12">
        <input class="btn btn-info" type="button" value="Back" (click)="goBack()" />
    </div>
    <div class="ResultsPage-Header row col-lg-12">
        <h1>Results: {{results.length}}</h1>
    </div>
    <div class="row">
        <div class="col-lg-1">
            <p>Filters:</p>
        </div>
        <div class="col-lg-11">
          <div class="ResultsPage-Filters" *ngFor="let filter of filters">
              <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>{{' '+filter.value}}
          </div>
        </div>
    </div>
    <div class="ResultsPage-List row" *ngIf="results">
        <div class="ResultsPage-ListItem col-lg-12" *ngFor="let result of results">
            <div class="card">
            <div class="card-header" (click)="goToDetails(result.id)">{{result.full_name}}</div>
            <div class="card-block">
                <div class="col-lg-4">City: {{result.city}}</div>
                <div class="col-lg-4">State: {{result.state}}</div>
            </div>
            </div>
        </div>
    </div>
    <div class="ResultsPage-Loading row" *ngIf="!results">
        Loading...
    </div>
</div>
