// react-app/src/Components/SearchPage/SearchPage.js
import React, { Component } from 'react';
import './SearchPage.css';
import Quicklinks from './Quicklinks/Quicklinks';
import Autocomplete from '../Common/Autocomplete/Autocomplete';
import {ClearAllFilters} from '../../Service/ManageFilters';

export default class SearchPage extends Component {
    constructor(props) {
        super(props);
        this.state = {
            linksList: ['state',
            'city',
            'eye_color',
            'language']
        }
        ClearAllFilters();
    }
    goToResultsPage() {
        this.history.push('/results');
    }
    render () {
        return (
            <div id="SearchPage container-fluid">
                <div className="SearchPage-AutoCompleteDiv row">
                    <div className="col-lg-12">
                        <div className="col-lg-1"><h4>Search:</h4></div> 
                        <div className="col-lg-11"><Autocomplete onChange={this.goToResultsPage} /></div> 
                    </div>
                </div>
                <div className="row">
                    {this.state.linksList.map((type) =>
                        <div className="col-lg-3">
                            <Quicklinks name={type} history={this.props.history} onClick={this.goToResultsPage} />
                        </div>
                    )}
                </div>
            </div>
        );
    }
}

// angular-app/src/app/Components/search-page/search-page.component.ts
import { FiltersService } from './../../Services/filters-service/filters-service.service';
import { RouterModule, Router } from '@angular/router';
import { DataService } from './../../Services/data-service/data-service.service';
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-search-page',
  templateUrl: './search-page.component.html',
  styleUrls: ['./search-page.component.css']
})
export class SearchPageComponent implements OnInit {
  linksList: string[];

  constructor(private _filterService: FiltersService,
    private _router: Router) { }

  ngOnInit() {
    this.linksList = ['state',
    'city',
    'eye_color',
    'language'];
    this._filterService.ClearAllFilters();
  }

  goToResultsPage() {
    this._router.navigate(['/results']);
  }
}

<div id="SearchPage container-fluid">
    <div class="SearchPage-AutoCompleteDiv row">
        <div class="col-lg-12">
            <div class="col-lg-1"><h6>Search:</h6></div>
            <div class="col-lg-11"><app-autocomplete (onClick)="goToResultsPage()"></app-autocomplete></div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-3" *ngFor="let type of linksList">
            <app-quicklinks [type]="type" (onClick)="goToResultsPage()"></app-quicklinks>
        </div>
    </div>
</div>
